/*This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
If a copy of the MPL was not distributed with this file, You can obtain one at
http://mozilla.org/MPL/2.0/.

The Original Code is the Files library.

The Initial Developer of the Original Code is
Mats 'Afr0' Vederhus. All Rights Reserved.

Contributor(s):
*/

namespace Files
{
  //Generated by Mr. Shipper - filenames have been sanitized, and does not match
  //actual filenames character for character!
  partial class FileIDs
  {
      public enum AnimationsFileIDs : long
      {
      };
  }
}
