using System;

namespace Files
{
  //Generated by Mr. Shipper - filenames have been sanitized, and does not match
  //actual filenames character for character!
  partial class FileIDs
  {
      public enum AnimationsFileIDs : long
      {
      };
  }
}
